---
title: "P7_Initial_Analysis"
author: "Kevin Rose"
date: "Last updated on: 7/4/2022"
output: 
  html_document: 
    toc: yes
    toc_float: yes
    theme: readable
    fig_width: 10
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is the initial analysis of the OMC-rich P7 scRNA-seq dataset using the Seurat pipeline. Steps included in the initial analysis:  

1) Loading in the P7 dataset:
  You will need the following cellranger outputs (filtered) which includes:
    1) barcodes.tsv  
    2) features.tsv  
    3) matrix.mtx
    
## Loading Data into Seurat

```{r, Data_Upload, warning = FALSE, message = FALSE}
#Libraries needed for analysis
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)

#P7 Cochlea from CellRanger
P7.data <- Read10X(data.dir = "./CellRanger/")
# Initialize the Seurat object with the raw (non-normalized data).
P7 <- CreateSeuratObject(counts = P7.data, project = "P7", min.cells = 3, min.features = 200)
rm(P7.data)
```


## Quality Control Steps

```{r, QC}
#Quality Control
#Mitochondrial Percentage
P7[['percent.mt']] <- PercentageFeatureSet(P7, pattern = '^mt-')
#Visualize QC metrics - VlnPlots
VlnPlot(P7, cols = 'cyan4', features = c('nFeature_RNA', 'nCount_RNA', 'percent.mt'), ncol = 3)
#QC ScatterPlots
plot1 <- FeatureScatter(P7, cols = 'cyan4', feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(P7, cols = 'cyan4', feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2
#cutoffs = percent_mt = 30% | nFeatures (genes) = 200 - 7500
P7 <- subset(P7, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 30)
```

